import { vec2 } from './Base';
import { Instance } from './Instance';
import { Rectangle } from './Rectangle';
import { Sprite } from './Sprite';
import { Base } from './Base';
export declare class Container {
    children: Array<Container | Rectangle>;
    localMatrix: Float32Array;
    worldMatrix: Float32Array;
    gl: WebGLRenderingContext;
    base: Base;
    parent: Container | Rectangle | Sprite;
    instances: Array<Instance>;
    x: number;
    y: number;
    og_width: number;
    og_height: number;
    width: number;
    height: number;
    private _angle;
    scale: vec2;
    transformationPoint: vec2;
    constructor(base: Base, x: number, y: number, w: number, h: number, transformationPoint?: vec2);
    addChild(child: any, createInstance?: boolean): void;
    setParent(parent: any): void;
    updateWorldMatrix(): void;
    moveTo(x: number, y: number): void;
    scaleAndRotate(): void;
    angle: number;
}
